In [1]:
import numpy as np

Задание 1

In [3]:
# Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Задание 2

In [6]:
# Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
a1 = a.reshape(2, 6)
a2 = a.reshape(6, 2)
a3 = a.reshape(3, 4)
a4 = a.reshape(4, 3)
a5 = a.reshape(12, 1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


Задание 3

In [7]:
# Создать 5 двумерных массивов разной формы из массива a. 
# Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).
a1 = a.reshape(2, -1)
a2 = a.reshape(-1, 2)
a3 = a.reshape(3, -1)
a4 = a.reshape(4, -1)
a5 = a.reshape(-1, 1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


Задание 4

In [8]:
# Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
print(a5[0])
print(a5[0,0])
# При обращении к первому элементу массива а5 по одному индексу получаем другой массив из одного элемента. 
# Если к первому элементу массива а5 обратиться по индексу строки и столбца, то получаем первый элемента массива а5. 
# Поэтому данный массив нельзяя назвать одномерным.

[12]
12


Задание 5

In [9]:
# Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального 
# распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0.
b=np.random.randn(3,4)
print(b)

[[ 0.76632936  0.43059025  0.48331406 -1.03995163]
 [-1.04647021  0.10196561  1.66456171  1.12515642]
 [ 0.16548238 -0.6221159   0.37693311  3.19967125]]


In [10]:
# Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.
print(b.size)
b=b.flatten()
print(b.size)
b

12
12


array([ 0.76632936,  0.43059025,  0.48331406, -1.03995163, -1.04647021,
        0.10196561,  1.66456171,  1.12515642,  0.16548238, -0.6221159 ,
        0.37693311,  3.19967125])

Задание 6

In [13]:
# Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


Задание 7

In [14]:
# Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.
b = np.arange(20, 1, -2).reshape(1,10)
print(b)

[[20 18 16 14 12 10  8  6  4  2]]


In [15]:
# В чем разница между массивами a и b?
print('Массив а - одномерный \nМассив b - двумерный')

Массив а - одномерный 
Массив b - двумерный


Задание 8

In [16]:
# Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
# чем число строк двумерного массива b, состоящего из единиц. 
# Итоговый массив v должен иметь атрибут size, равный 10.
a = np.zeros((2, 2))
b = np.zeros((3, 2))+1
v = np.vstack((a, b))
print(a)
print(b)
print(v)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [18]:
# Итоговый массив v должен иметь атрибут size, равный 10.
a.shape, b.shape, v.shape, v.size


((2, 2), (3, 2), (5, 2), 10)

Задание 9

In [20]:
# Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
a=np.arange(0, 12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [21]:
# Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.
A=a.reshape(4,3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [22]:
# Получить матрицу At путем транспонирования матрицы A. 
At=A.T
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [23]:
# Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
B = np.dot(A, At)
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [24]:
# Какой размер имеет матрица B? 
B.shape

(4, 4)

In [25]:
#Получится ли вычислить обратную матрицу для матрицы B и почему?
B_inv=np.linalg.inv(B)
print(B)
# Матрица B - вырожденная, поэтому определитель для неёё вычислить невозможно

LinAlgError: Singular matrix

Задание 10

In [26]:
# Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
np.random.seed(42)

Задание 11

In [27]:
# Создайте одномерный массив c, составленный из последовательности 
# 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.
c=np.random.randint(0, 16,16)
print(c)

[ 6  3 12 14 10  7 12  4  6  9  2  6 10 10  7  4]


Задание 12

In [28]:
#Поменяйте его форму так, чтобы получилась квадратная матрица C.
C=c.reshape(4,4)
print(C)

[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


In [29]:
# Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. 
D=B+C*10
print(D)

[[ 65  44 143 172]
 [114 120 206 162]
 [ 83 176 169 272]
 [132 222 282 342]]


In [31]:
# Вычислите определитель, ранг и обратную матрицу D_inv для D.
det_D = np.linalg.det(D)
rank_D = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)
print(det_D)
print(rank_D)
print(D_inv)

-28511999.999999944
4
[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


Задание 12

In [32]:
# Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
# Убедитесь, что в матрице D_inv остались только нули и единицы. 
D_inv=np.where(D_inv<0, 0,1)
print(D_inv)

[[1 1 1 0]
 [0 0 0 1]
 [0 0 0 1]
 [1 0 1 0]]


In [34]:
# С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы 
# B и C - в качестве источников данных, получите матрицу E размером 4x4.  
# Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, 
# должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых 
# соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

print(B)
print(C)
E=np.where(D_inv==1, B, C)
E


[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])